listKata = ["mangga", "jambu", "apel", "anggur"]
print(listKata[0:])
print(listKata[1:])
print(listKata[2:])
print(listKata[3:])
print(listKata[0:-1])
print(listKata[0:-2])
print(listKata[0:-3])
print(listKata[0:-4])
print()
print(listKata[-1:])
print(listKata[-2:])
print(listKata[-3:])
print(listKata[-4:])
print(listKata[:-1])
print(listKata[:-2])
print(listKata[:-3])
print(listKata[:-4])